
name: Python CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Python
        run: python3 --version

      - name: Install dependencies
        run: |
          python3 -m venv venv-ci
          source venv-ci/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv-ci/bin/activate
          pytest
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/khoin06/ci-cd-lab:latest .

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ghcr.io/khoin06/ci-cd-lab:latest
      - name: Deploy to master-02
        run: |
          ssh master-02@192.168.56.12 '
            docker pull ghcr.io/khoin06/ci-cd-lab:latest &&
            docker stop ci-cd-app || true &&
            docker rm ci-cd-app || true &&
            docker run -d \
              --name ci-cd-app \
              -p 5000:5000 \
              ghcr.io/khoin06/ci-cd-lab:latest
          '
