
name: Python CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Python
        run: python3 --version

      - name: Install dependencies
        run: |
          python3 -m venv venv-ci
          source venv-ci/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv-ci/bin/activate
          pytest
      - name: Build Docker image
        run: |
          docker build -t ci-cd-lab:latest .
